name: Nightly Releases

on:
  schedule:
    - cron:  '1 1 * * *'

jobs:
  check:
    runs-on: ubuntu-latest
    
    outputs:
      status: ${{ steps.check.outputs.status }}
    
    steps:
    - uses: actions/checkout@master
      name: checkout
    
    - run: ./bintray_nightly_check.sh; echo "::set-output name=status::$?"
      name: nightly-check
      id: check
      shell: bash {0}
      env:
        BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
        BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
  
  build-docker:
  
    needs: check
    if: needs.check.outputs.status == 0
  
    runs-on: ubuntu-latest
    
    container:
      image: docker://justdan96/tsmuxer_build:latest
      volumes:
      - /workspace:/github/workspace
    
    steps:
    - uses: actions/checkout@master
      name: checkout
      
    - run: rm -f bin/.gitkeep
      name: clean-bin-folder
      
    - run: ./rebuild_linux_with_gui_docker.sh
      name: build-for-linux
      
    - run: ./rebuild_mxe_with_gui_docker.sh
      name: build-for-win64
      
    - run: ./rebuild_mxe32_with_gui_docker.sh
      name: build-for-win32
      
    - run: ./bintray_nightly_upload.sh
      name: upload-to-bintray-nightly
      env:
        BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
        BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
        OBS_USER: ${{ secrets.OBS_USER }}
        OBS_SECRET: ${{ secrets.OBS_SECRET }}
  
  build-macos:
  
    needs: check
    if: needs.check.outputs.status == 0
    
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@master
      name: checkout
    
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      
    - run: ./build_macos_native.sh
      name: build-for-mac
    
    - run: ./bintray_nightly_upload.sh ./build/bin/mac.zip mac
      name: upload-bintray-mac-build
      env:
        BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
        BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
